name: Deploy NISAR docs test site

on:
  push:
    branches: [develop]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Deploy docs site
        uses: ./.github/actions/deploy-docs
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          s3-bucket: ${{ secrets.S3_BUCKET }}
          distribution-id: ${{ secrets.DISTRIBUTION_ID }}
          domain: ${{ vars.DEPLOYMENT_DOMAIN }}
